### ISSUE TITLE
Loxone Gen 2 with v12.0.2.24 not working

### ISSUE THREAD

**Issue by JBChesh** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#64]
Just upgraded my Loxone to a Gen 2 unit, restoring all settings from the old Gen 1 and although I can see the UDP packets being read by the Loxone, it's not acknowledging the data.  It seems other people have commented similar issues.

Happy to provide any info if it would help.

**Comment by mschlenstedt** [comment]
UDP and HTTP inputs should work as usual, But due to a bug in name resolving the weather emulator does not work with V12. Loxone has to fix this.

**Comment by JBChesh** [comment]
Okay thanks for the update.  Let’s hope they do so soon.

Joel Becker
________________________________

**Comment by mschlenstedt** [comment]
Well, not sure if they do so. "Normal" users will not have any issues, except that the Google DNS will be used more or less permanently instead of your configuried DNS servers.

There are some workaounds to use Weather4Lox with V12 (block Google DNS in your Router for example). Details are here (in german unfortuntely):  https://www.loxforum.com/forum/projektforen/loxberry/plugins/157182-plugin-weather4lox-ehemals-wunderground4loxone (last 2-3 pages).

I will close it here because I cannot do anything about that.
