### ISSUE TITLE
Weather codes for open weather map incorrectly mapped

### ISSUE THREAD

**Issue by uKL** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#71]
Hi,
I've noticed that weather codes defined here https://openweathermap.org/weather-conditions
are not correctly mapped to descriptions in grabber_openweather.pl

For example
Tornado => fog
Squall => fog

**Comment by mr-manuel** [comment]
Hi, if you look in the icons folder (https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/tree/master/webfrontend/html/icons), there are no icons for this cases. To be more dramatic I changed them to thunderstorms icon.

I will open a pull request, where I added/removed entries so that it corresponds to your link. Before I have to wait, that my current pull request is accepted.

**Comment by mschlenstedt** [comment]
Fixed with #75
